spring:
  data:
    web:
      pageable:
        one-indexed-parameters: true # 페이지 조회시 1부터 시작
        default-page-size: 5
  jpa:
    defer-datasource-initialization: on
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;Mode=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

jwt:
  secret-key: c3VwZXJsb25nc3RyaW5nc2VjcmV0a2V5LS0tLWFzZGFzZGFz