spring:
  data:
    web:
      pageable:
        one-indexed-parameters: true # 페이지 조회시 1부터 시작
        default-page-size: 5
  jpa:
    defer-datasource-initialization: on
  sql:
    init:
      mode: always